<?php
/**
 * Localizations for the Roundrive plugin
 *
 * @version @package_version@
 * @author Klaus Rörig <kroerig@gmail.com>
 *
 * This plugin is inspired by kolab_files plugin
 * Use flysystem library : https://github.com/thephpleague/flysystem
 * With flysystem WebDAV adapter : https://github.com/thephpleague/flysystem-webdav
 *
 * Copyright (C) 2015 PNE Annuaire et Messagerie MEDDE/MLETR
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$labels['files'] = 'Dateien';
$labels['filepreview'] = 'Vorschau';
$labels['saveall'] = 'Alle in die Cloud speichern';
$labels['saveto'] = 'In die Cloud speichern';
$labels['saveas'] = 'Speichern unter:';
$labels['create'] = 'Erstellen';
$labels['save'] = 'Speichern';
$labels['cancel'] = 'Abbrechen';
$labels['fromcloud'] = 'Aus der Cloud...';
$labels['selectfiles'] = 'Dateien zum Anhängen auswählen';
$labels['attachsel'] = 'Ausgewählte anhängen';
$labels['foldercreate'] = 'Verzeichnis erstellen';
$labels['folderdelete'] = 'Verzeichnis löschen';
$labels['folderinside'] = 'Hier einfügen';
$labels['foldername'] = 'Verzeichnisname';
$labels['name'] = 'Name';
$labels['mtime'] = 'Geändert';
$labels['type'] = 'Type';
$labels['upload'] = 'Hochladen';
$labels['uploadfile'] = 'Datei(en) hochladen';
$labels['get'] = 'Herunterladen';
$labels['getfile'] = 'Datei herunterladen';
$labels['view'] = 'Ansehen';
$labels['viewfile'] = 'Datei ansehen';
$labels['rename'] = 'Datei umbenennen';
$labels['deletefile'] = 'Datei(en) löschen';
$labels['edit'] = 'Bearbeiten';
$labels['editfile'] = 'Datei bearbeiten';
$labels['save'] = 'Speichern';
$labels['savefile'] = 'Datei speichern';
$labels['printfile'] = 'Datei drucken';
$labels['fileedit'] = 'Eigenschaften';
$labels['collection_audio'] = 'Musik';
$labels['collection_video'] = 'Videos';
$labels['collection_image'] = 'Bilder';
$labels['collection_document'] = 'Dokumente';
$labels['uploading'] = 'Hochladen...';
$labels['attaching'] = 'Anfängen...';
$labels['foldercreating'] = 'Erstelle Ordner...';
$labels['folderupdating'] = 'Aktualisiere Ordner...';
$labels['folderdeleting'] = 'Lösche Ordner';
$labels['folderdeleteconfirm'] = 'Wollen Sie den Ordner wirklich löschen?';
$labels['folderdeletenotice'] = 'Ordner erfolgreich gelöscht.';
$labels['folderupdatenotice'] = 'Ordner erfolgreich aktualisiert.';
$labels['foldercreatenotice'] = 'Ordner erfolgreich erstellt.';
$labels['saveallnotice'] = '$n Datei(en) erfolgreich gespeichert.';
$labels['saveallerror'] = 'Speichern von $n Datei(en) fehlgeschlagen.';
$labels['attacherror'] = 'Anfügen von Dateien fehlgeschlagen';
$labels['fileupdating'] = 'Aktualisiere Datei...';
$labels['filemoving'] = 'Verschiebe Datei(en)...';
$labels['filecopying'] = 'Kopiere Datei(en)...';
$labels['filedeleting'] = 'Lösche Datei(en)...';
$labels['filedeleteconfirm'] = 'Wollen Sie die Datei(en) wirklich löschen?';
$labels['filedeletenotice'] = 'Datei(en) erfolgreich gelöscht.';
$labels['filemovenotice'] = 'Datei(en) erfolgreich verschoben.';
$labels['filecopynotice'] = 'Datei(en) erfolgreich kopiert.';
$labels['uploadsizeerror'] = 'Maximale Dateigröße ($size) überschritten!';
$labels['allfolders'] = 'suche in allen Ordnern';
$labels['fileskip'] = 'Überspringen';
$labels['fileskipall'] = 'Alle überspringen';
$labels['fileoverwrite'] = 'Überschreiben';
$labels['fileoverwriteall'] = 'Alle überschreiben';
$labels['filemoveconfirm'] = 'Diese Aktion wird folgende Datei überschreiben: <b>$file</b>.';
$labels['arialabelsearchform'] = 'Dateisuche';
$labels['arialabelquicksearchbox'] = 'Search input';
$labels['arialabellistoptions'] = 'Files list options';
$labels['arialabelfolderoptions'] = 'Folder actions';
$labels['arialabelfileeditform'] = 'File editing form';
$labels['arialabelfoldercreateform'] = 'Folder creation form';
$labels['arialabelfoldereditform'] = 'Folder editing form';
$labels['arialabelfolderlist'] = 'Folder/Collection selection';
$labels['arialabelfileselectdialog'] = 'File selection dialog';
$labels['arialabelattachmentoptions'] = 'Attachment save options';
$labels['arialabelfilesavedialog'] = 'Speichern unter Fenster';
$labels['arialabelfileprops'] = 'Dateieigenschaften';
$labels['arialabelfilecontent'] = 'Dateiinhalt';

?>
