<?php
/**
 * Localizations for the Roundrive plugin
 *
 * @version @package_version@
 * @author Thomas Payen <thomas.payen@apitech.fr>
 *
 * This plugin is inspired by kolab_files plugin
 * Use flysystem library : https://github.com/thephpleague/flysystem
 * With flysystem WebDAV adapter : https://github.com/thephpleague/flysystem-webdav
 *
 * Copyright (C) 2015 PNE Annuaire et Messagerie MEDDE/MLETR
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

$labels['files'] = 'Arquivos';
$labels['filepreview'] = 'Pré-visualização de arquivo';
$labels['saveall'] = 'Salvar todos na nuvem';
$labels['saveto'] = 'Salvar na nuvem...';
$labels['saveas'] = 'Salvar como:';
$labels['create'] = 'Criar';
$labels['save'] = 'Salvar';
$labels['cancel'] = 'Cancelar';
$labels['fromcloud'] = 'Da nuvem...';
$labels['selectfiles'] = 'Selecione o(s) arquivo(s) para anexar...';
$labels['attachsel'] = 'Anexo selecionado';
$labels['foldercreate'] = 'Criar pasta';
$labels['folderdelete'] = 'Excluir pasta';
$labels['folderinside'] = 'Inserir dentro';
$labels['foldername'] = 'Nome da pasta';
$labels['name'] = 'Nome';
$labels['mtime'] = 'Modificado';
$labels['type'] = 'Tipo';
$labels['upload'] = 'Carregar';
$labels['uploadfile'] = 'Carregar arquivo(s)';
$labels['get'] = 'Baixar';
$labels['getfile'] = 'Baixar arquivo';
$labels['view'] = 'Ver';
$labels['viewfile'] = 'Ver arquivo';
$labels['rename'] = 'Renomear arquivo';
$labels['deletefile'] = 'Excluir arquivo(s)';
$labels['edit'] = 'Editar';
$labels['editfile'] = 'Editar arquivo';
$labels['save'] = 'Salvar';
$labels['savefile'] = 'Salvar arquivo';
$labels['printfile'] = 'Imprimir arquivo';
$labels['fileedit'] = 'Propriedades do arquivo';
$labels['collection_audio'] = 'Áudio';
$labels['collection_video'] = 'Vídeo';
$labels['collection_image'] = 'Imagens';
$labels['collection_document'] = 'Documentos';
$labels['uploading'] = 'Carregando arquivo(s)...';
$labels['attaching'] = 'Anexando arquivo(s)...';
$labels['foldercreating'] = 'Criando pasta...';
$labels['folderupdating'] = 'Carregando pasta...';
$labels['folderdeleting'] = 'Excluindo pasta...';
$labels['folderdeleteconfirm'] = 'Está certo que deseja excluir as pastas selecionadas?';
$labels['folderdeletenotice'] = 'Pasta excluida com sucesso.';
$labels['folderupdatenotice'] = 'Pasta atualizada com sucesso.';
$labels['foldercreatenotice'] = 'Pasta criada com sucesso.';
$labels['saveallnotice'] = 'Salvo com sucesso $n arquivo(s).';
$labels['saveallerror'] = 'Salvamento de $n arquivo(s) falhou.';
$labels['attacherror'] = 'Falha ao anexar arquivo(s) da nuvem';
$labels['fileupdating'] = 'Atualizando arquivo...';
$labels['filemoving'] = 'Movendo arquivo(s)...';
$labels['filecopying'] = 'Copiando arquivo(s)...';
$labels['filedeleting'] = 'Excluindo arquivo(s)...';
$labels['filedeleteconfirm'] = 'Está certo que deseja excluir os arquivos selecionados?';
$labels['filedeletenotice'] = 'Arquivo(s) excluido com sucesso.';
$labels['filemovenotice'] = 'Arquivo(s) movido com sucesso.';
$labels['filecopynotice'] = 'Arquivo(s) copiado com sucesso.';
$labels['uploadsizeerror'] = 'Tamanho máximo de arquivo ($size) excedido!';
$labels['allfolders'] = 'procurar em todas as pastas';
$labels['fileskip'] = 'Pular';
$labels['fileskipall'] = 'Pular todos';
$labels['fileoverwrite'] = 'Sobrescrever';
$labels['fileoverwriteall'] = 'Sobrescrever todos';
$labels['filemoveconfirm'] = 'Esta ação irá sobrescrever o arquivo destino: <b>$file</b>.';
$labels['arialabelsearchform'] = 'Formulário de busca de arquivos';
$labels['arialabelquicksearchbox'] = 'Entrada de busca';
$labels['arialabellistoptions'] = 'Lista de opções de arquivos';
$labels['arialabelfolderoptions'] = 'Ações de pasta';
$labels['arialabelfileeditform'] = 'Formulário de edição de arquivo';
$labels['arialabelfoldercreateform'] = 'Formulário de criação de pasta';
$labels['arialabelfoldereditform'] = 'Formulário de edição de pasta';
$labels['arialabelfolderlist'] = 'Seleção de pasta/coleção';
$labels['arialabelfileselectdialog'] = 'Diálogo de seleção de arquivo';
$labels['arialabelattachmentoptions'] = 'Opções de salvamento de anexos';
$labels['arialabelfilesavedialog'] = 'Diálogo de salvamento de Arquivo(s)';
$labels['arialabelfileprops'] = 'Propriedades do arquivo';
$labels['arialabelfilecontent'] = 'Conteúdo do arquivo';

?>
